apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: banking
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080