apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend
  namespace: banking

spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node-1
      containers:
        - name: frontend
          image: vishwajeetkumar938/java-banking-frontend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80