apiVersion: v1
kind: Secret
metadata:
  name: postgress-secret
  namespace: banking
type: Opaque
stringData:
  POSTGRESS_DB: bankingdb
  POSTGRESS_USER: banking_user
  POSTGRESS_PASSWORD: banking_pass123
