apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: banking
type: Opaque
stringData:
  POSTGRES_DB: bankingdb
  POSTGRES_USER: banking_user
  POSTGRES_PASSWORD: banking_pass123
