prometheus:
  prometheusSpec:
    retention: 15d
    nodeSelector:
      kubernetes.io/hostname: monitoring-node
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

grafana:
  nodeselector:
    kubernetes.io/hostname: monitoring-node
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi
  adminPassword: "StrongPassword123!"
  service:
    type: NodePort
    nodePort: 30090

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/hostname: monitoring-node
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

serice:
  type: NodePort
  nodePort: 30093
config:
  global:
    resolve_timeout: 5m
  route:
    receiver: 'discord-notifications'
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    route:
      - receiver: 'null'
        matchers:
          - alertname=~ "Watchdog|Kube.*Unreachable|Alertmanager.*Failed.*|etcd.*"
  receivers:
    - name: 'null'
    - name: 'discord-notifications'
      discord_configs:
        - api_url: 'https://discord.com/api/webhooks/1533798419234295841/z5cYLEnZ8tb2CTPbsTVoxSSdp2_J3LVctzS0S_RnVmAtYoM6LD3ug8B12ChsOQ9CvqXr'
            

additionalPrometheusRulesMap:
  custom-crashloop-rule:
    groups:
      - name: custom-kubernetes-apps
        rules:
          - alert: kubePodCrashLoopingFast
            expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[5m]) >= 1
            for: 30s
            labels:
              severity: warning
            annotation:
              description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is in CrashLoopBackOff"

          - alert: kubePodOOMKilled
            expr: kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} == 1
            for: 10s
            labels:
              severity: critical
            annotation:
              description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} container {{ $labels.container }} was OOMKilled"